### ISSUE TITLE
Cannot download png image from s3

### ISSUE THREAD

**Issue by alexch2000** [swift-aws/s3#1]
Hi, 
I am using SwiftAWSS3, but it cannot download image - there is an exception throw in XML parsing
```
let s3Client = S3(accessKeyId: "",
                      secretAccessKey: "",
                      region: Region.eucentral1,
                      endpoint: "https://apigateway.eu-central-1.amazonaws.com"
    )
let request = S3.GetObjectRequest(bucket: bucketName, key: "2017/08/image-620x826.png")
let object = try s3Client.getObject(request)
            
if let body = object.body {
     return ImageResource(data: body)
}
```

This code can return image when I use another ServiceProtocol in S3 client creation

```
 ServiceProtocol(type: .other("image"))
```

Do I do something wrong?

**Comment by noppoMan** [comment]
@alexch2000 
sorry for too rate replying...

Now I'm back to this project and working for Swift 4.
I'll check this issue together.
