### ISSUE TITLE
`createBucket` request fails with 409 (conflict), but doesn't throw

### ISSUE THREAD

**Issue by mxcl** [swift-aws/s3#3]
When making a create bucket request for an already existing bucket the future succeeds but the operation in fact failed.

Stepping through the framework code in a debugger the first (or second) HTTP request is a 409, but the future is not rejected.

**Comment by mxcl** [comment]
```swift
let createBucketRequest = S3.CreateBucketRequest(bucket: bucket)
return try s3.createBucket(createBucketRequest)
```

**Comment by adam-fowler** [comment]
@mxcl Code in here was so old, surprised it worked at all. I've just updated it with latest from aws-sdk-swift if you want to give it another go.

**Comment by adam-fowler** [comment]
fixed
