### ISSUE TITLE
Crash in S3RequestMiddleware (due to optional bang)

### ISSUE THREAD

**Issue by mxcl** [swift-aws/s3#4]
https://github.com/swift-aws/s3/blob/9deea717490c08c5dac87e8b818cbdb2b227c7e6/Sources/SwiftAWSS3/S3RequestMiddleware.swift#L40

We’re getting a crash here for filenames with spaces in them.

Our fix locally is to percent encode the key, but well, we should remove this bang, it's not safe. Either throw or percent encode ourselves (possibly thus percent encoding *twice*, not sure if there's a logical way to prevent that).

Happy to PR, LMK what you think.

**Comment by adam-fowler** [comment]
@mxcl Code in here was so old, surprised it worked at all. I've just updated it with latest from aws-sdk-swift if you want to give it another go.

**Comment by adam-fowler** [comment]
this is fixed
